Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -71,21 +71,24 @@ jobs:
 
     - name: Create or Update ECS Service
       run: |
-        SERVICE_NAME=$(aws ecs describe-services --cluster chat-app-cluster --services chat-app-service --query "services[0].serviceName" --output text 2>/dev/null || echo "none")
-        if [ "$SERVICE_NAME" == "none" ]; then
-          echo "Creating service..."
-          aws ecs create-service \
-            --cluster chat-app-cluster \
-            --service-name chat-app-service \
-            --task-definition chat-app-task \
-            --desired-count 1 \
-            --launch-type FARGATE \
-            --network-configuration "awsvpcConfiguration={subnets=[subnet-0ce2c05e1bf7aaccc,subnet-054b3215eb590a52c],securityGroups=[sg-0072874a3e4210f1c],assignPublicIp=ENABLED}"
-        else
-          echo "Service already exists, updating..."
-          aws ecs update-service \
-            --cluster chat-app-cluster \
-            --service chat-app-service \
-            --task-definition chat-app-task \
-            --force-new-deployment
-        fi
+       SERVICE_NAME=$(aws ecs describe-services --cluster chat-app-cluster --services chat-app-service --query "services[0].serviceName" --output text 2>/dev/null || echo "none")
+       if [ "$SERVICE_NAME" == "none" ]; then
+       echo "Service not found, creating new service..."
+       aws ecs create-service \
+        --cluster chat-app-cluster \
+        --service-name chat-app-service \
+        --task-definition chat-app-task \
+        --desired-count 1 \
+        --launch-type FARGATE \
+        --network-configuration "awsvpcConfiguration={subnets=[subnet-12345,subnet-67890],securityGroups=[sg-0123456789abcdef0],assignPublicIp=ENABLED}"
+       else
+        echo "Service already exists, updating..."
+        aws ecs update-service \
+        --cluster chat-app-cluster \
+        --service chat-app-service \
+        --task-definition chat-app-task \
+        --force-new-deployment
+       fi
+
+
+   
